from typing import Protocol, Optional, List
from ..models.user import User
from ..models.employee import Employee

class UserRepositoryPort(Protocol):
    """Puerto para persistencia de usuarios (ISO 27001: A.9.2.6)"""
    def save(self, user: User) -> User: ...
    def find_by_username(self, username: str) -> Optional[User]: ...
    def find_by_id(self, id: int) -> Optional[User]: ...
    def audit_action(self, user_id: int, action: str) -> None: ...  # ISO 27001: A.12.4.1

class EmployeeRepository(Protocol):
    def save(self, employee: Employee) -> Employee: ...
    def find_by_id(self, id: int) -> Optional[Employee]: ...
    def find_all(self) -> List[Employee]: ...